NumPy

It provides a high- performance multidimensional array object, and tools for working with these arrays.

In [27]:
import numpy as np
# Create a rank 1 array
a = np.array([0, 1, 2])
print(type(a))
# this will print the dimension of the array
print (a.shape)
print (a[0])
print (a[1])
print (a[2])
# Change an element of the array
a[0] = 5
print (a)

# Create a rank 2 array
b = np.array([[0,1,2],[3,4,5]]) 
print (b.shape)
print (b)
print (b[0, 0], b[0, 1], b[1, 0])

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]
(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


Creating NumPy Array

In [28]:
# Create a 3x3 array of all zeros
a = np.zeros((3,3))
print (a)

# Create a 2x2 array of all ones
b = np.ones((2,2))
print (b)

# Create a 3x3 constant array
c = np.full((3,3), 7)
print (c)

# Create a 3x3 array filled with random values
d = np.random.random((3,3))
print (d)

# Create a 3x3 identity matrix
e = np.eye(3)
print (e)

# convert list to array
f = np.array([2, 3, 1, 0])
print (f)

# arange() will create arrays with regularly incrementing values
g = np.arange(20)
print (g)

# note mix of tuple and lists
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
print (h)

# create an array of range with float data type
i = np.arange(1, 8, dtype=float)
print (i)

# linspace() will create arrays with a specified number of items which are
# spaced equally between the specified beginning and end values
j = np.linspace(2., 4., 5)
print (j)

# indices() will create a set of arrays stacked as a one-higher
# dimensioned array, one per dimension with each representing variation
# in that dimension
k = np.indices((2,2))
print (k)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.52823845 0.72094128 0.19713572]
 [0.75413937 0.41661246 0.8199412 ]
 [0.51711821 0.75542047 0.41291705]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2 3 1 0]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]
[1. 2. 3. 4. 5. 6. 7.]
[2.  2.5 3.  3.5 4. ]
[[[0 0]
  [1 1]]

 [[0 1]
  [0 1]]]


Data Types

In [29]:
# Let numpy choose the datatype
x = np.array([0, 1])
y = np.array([2.0, 3.0])
# Force a particular datatype
z = np.array([5, 6], dtype=np.int64)
print (x.dtype, y.dtype, z.dtype)

int64 float64 int64


Array Indexing
There are three kinds of indexing available:
• Field access
• Basic slicing
• Advanced indexing

• Field access
If the ndarray object is a structured array, the fields of the array can be accessed by indexing the array with strings, dictionary like. Indexing x[‘field-name’] returns a new view to the array, which is of the same shape as x, except when the field is a subarray, but of data type x.dtype[‘field-name’] and contains only the part of the data in the specified field.

In [30]:
x = np.zeros((3,3), dtype=[('a', np.int32), ('b', np.float64, (3,3))])
print ("x['a'].shape: ",x['a'].shape)
print ("x['a'].dtype: ", x['a'].dtype)
print ("x['b'].shape: ", x['b'].shape)
print ("x['b'].dtype: ", x['b'].dtype)

x['a'].shape:  (3, 3)
x['a'].dtype:  int32
x['b'].shape:  (3, 3, 3, 3)
x['b'].dtype:  float64


• Basic slicing
NumPy arrays can be sliced, similar to lists. You must specify a slice for each dimension of the array as the arrays may be multidimensional.
The basic slice syntax is i: j: k, where i is the starting index, j is the stopping index, and k is the step and k is not equal to 0. This selects the m elements in the corresponding dimension, with index values i, i + k, ...,i + (m - 1) k where m = q + (r not equal to 0) and q and r are the quotient and the remainder is obtained by dividing j - i by k: j - i = q k + r, so that i + (m - 1) k < j.

In [31]:
x = np.array([5, 6, 7, 8, 9])
x[1:7:2]

print (x[-2:5])
print (x[-1:1:-1])

y = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print ("Shape of y: ", x.shape)
y[1:3]

np.array([[[4], [5], [6]], [7]], dtype=object)
x[...,0]

# Create a rank 2 array with shape (3, 4)
a = np.array([[5,6,7,8], [1,2,3,4], [9,10,11,12]])
print ("Array a:", a)
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print ("Array b:", b)
print (a[0, 1])
b[0, 0] = 77
print (a[0, 1])

row_r1 = a[1,:]# Rank 1 view of the second row of a
row_r2 = a[1:2,:]# Rank 2 view of the second row of a
print (row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print (row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print (col_r2, col_r2.shape)

[8 9]
[9 8 7]
Shape of y:  (5,)
Array a: [[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
Array b: [[6 7]
 [2 3]]
6
77
[1 2 3 4] (4,)
[[1 2 3 4]] (1, 4)
[77  2 10] (3,)
[[77]
 [ 2]
 [10]] (3, 1)


• Advanced indexing
Integer array indexing: Integer array indexing allows you to construct random arrays and other arrays.

In [32]:
# An example of integer array indexing.
# The returned array will have shape (2,) and
print (a[[0, 1], [0, 1]])
# The above example of integer array indexing is equivalent to this:
print (np.array([a[0, 0], a[1, 1]]))  

# When using integer array indexing, you can reuse the same
# element from the source array:
print (a[[0, 0], [1, 1]])
# Equivalent to the previous integer array indexing example
print (np.array([a[0, 1], a[0, 1]]))

a=np.array([[1,2], [3, 4], [5, 6]])
# Find the elements of a that are bigger than 2
print (a > 2)
# to get the actual value
print (a[a > 2])

[5 2]
[5 2]
[77 77]
[77 77]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


Array Math

In [33]:
import numpy as np
x=np.array([[1,2],[3,4],[5,6]])
y=np.array([[7,8],[9,10],[11,12]])
# Elementwise sum; both produce the array
print(x+y)
print(np.add(x, y))

# Elementwise difference; both produce the array
print(x-y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
print(x*y)
print(np.multiply(x, y))
# Elementwise division; both produce the array
print(x/y)
print(np.divide(x, y))
# Elementwise square root; produces the array
print(np.sqrt(x))

x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
a=np.array([9,10])
b=np.array([11, 12])
# Inner product of vectors; both produce 219
print(a.dot(b))
print(np.dot(a, b))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(a))
print(np.dot(x, a))

# Matrix / matrix product; both produce the rank 2 array
print(x.dot(y))
print(np.dot(x, y))

x=np.array([[1,2],[3,4]])
# Compute sum of all elements
print(np.sum(x))
# Compute sum of each column
print(np.sum(x, axis=0))
# Compute sum of each row
print(np.sum(x, axis=1))

x=np.array([[1,2], [3,4]])
print(x)
print(x.T)

# Note that taking the transpose of a rank 1 array does nothing:
v=np.array([1,2,3])
print(v)
print(v.T)

[[ 8 10]
 [12 14]
 [16 18]]
[[ 8 10]
 [12 14]
 [16 18]]
[[-6 -6]
 [-6 -6]
 [-6 -6]]
[[-6 -6]
 [-6 -6]
 [-6 -6]]
[[ 7 16]
 [27 40]
 [55 72]]
[[ 7 16]
 [27 40]
 [55 72]]
[[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]
[[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]
219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
10
[4 6]
[3 7]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


Broadcasting

In [34]:
# create a matrix
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
# create a vector
v = np.array([1, 0, 1])
# create an empty matrix with the same shape as a
b = np.empty_like(a)
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(3):
    b[i, :] = a[i, :] + v
print(b)

# Stack 3 copies of v on top of each other
vv = np.tile(v, (3, 1))
print (vv)

# Add a and vv elementwise
b = a + vv
print (b)

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1, 0, 1])
# Add v to each row of a using broadcasting b=a+ v
print (b)

# Compute outer product of vectors
# v has shape (3,)
v = np.array([1,2,3])
# w has shape (2,)
w = np.array([4,5])
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
print (np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3],[4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3)
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column
print((x.T + w).T)

# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w,(2,1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3)
print(x * 2)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
[[1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
